name: Run Preprocessing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run preprocessing script
        run: python preprocessing/automate_Agus-Saputra-Kambea.py

      - name: Upload preprocessing result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hasil-preprocessing
          path: preprocessing/banking-data_preprocessing.csv
